swagger: '2.0'
info:
  version: 0.0.1
  title: Notification Service
host: localhost:8080
basePath: "/"
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  "/snippets":
    x-swagger-router-controller: NotificationService
    get:
      description: Returns all snippets
      operationId: returnSnippet
      responses:
        '200':
          description: Success
          schema:
            "$ref": "#/definitions/SnippetsResponse"
        default:
          description: Error
          schema:
            "$ref": "#/definitions/ErrorSnippetsResponse"
  "/swagger":
    x-swagger-pipe: swagger_raw
definitions:
  SnippetsResponse:
    required:
    - message
    properties:
      message:
        type: string
  ErrorSnippetsResponse:
    required:
    - message
    properties:
      message:
        type: string
